### ISSUE TITLE
Minify failed

### ISSUE THREAD

**Issue by Ayagoumi** [filipjelic/ActivityDetector#2]
@filipjelic when trying to build the project I am getting an error message "Failed to minify the code from this file:"

**Comment by filipjelic** [comment]
@Ayagoumi Could you post some steps so I can investigate it a little bit further?
What did you do after cloning the project?

**Comment by Ayagoumi** [comment]
After `yarn add react-activity-detector` on my project, I added it to my code, but when I tried to build the project, I am getting an error message 

```
Failed to minify the code from this file:

 	./node_modules/react-activity-detector/lib/ActivityDetector.js:1:1296
```

**Comment by filipjelic** [comment]
@Ayagoumi  What version of `react-scripts` are you using on your project? Also is the project open source so I can take a look more closely?
